
CREATE OR REPLACE VIEW "RESOURCE_CAPACITY"."PNMAC"."VW_FORECASTANDACTUALCOMBINEDINFO" AS SELECT
EFFORT_ID
,EFFORT_NAME
,PROJECT_ID
,PROJECT_NAME
,MILESTONE_ID
,MILESTONE_NAME
,PHASE_ID
,PHASE_NAME
,RELEASE_ID
,RELEASE_NAME
,EFFORT_ID as ITEM_ID
,EFFORT_NAME as ITEM_NAME
,EMPLOYEE_WORKING_TEAM_ID as WORKING_TEAM_SUB_DIVISION_ID
,EMPLOYEE_WORKING_TEAM as WORKING_TEAM_SUB_DIVISION_NAME
,BILLED_SUB_DIVISION_ID as BILLABLE_TO_SUB_DIVISION_ID
,BILLED_SUB_DIVISION_NAME as BILLABLE_TO_SUB_DIVISION_NAME
,null as EFFORT_TYPE
,YEAR
,QUARTER
,MONTH
,WEEK
,ENTRY_DATE as WEEK_DATE
,FIRST_OF_THE_MONTH
,EMPLOYEE_ID
,EMPLOYEE_PREFERRED_NAME
,(CASE WHEN EMPLOYEE_SERVICE_PROVIDER in ('PennyMac','Contractor') THEN 'Full Time' 
  WHEN EMPLOYEE_SERVICE_PROVIDER in ('Infosys','Sonata') THEN 'Offshore'
  ELSE 'Unknown' END ) as EMPLOYEE_TYPE
,EMPLOYEE_TITLE
,EMPLOYEE_TITLE_SHORT
,EMPLOYEE_EMPLOYMENT_TYPE
,EMPLOYEE_SERVICE_PROVIDER
,EMPLOYEE_WORKING_TEAM_ID as EMPLOYEE_SUB_DIVISION_ID
,(CASE WHEN EMPLOYEE_EMPLOYMENT_STATUS in ('Active','LOA') THEN 'Y' ELSE 'N' END) as EMPLOYEE_ACTIVE
,EMPLOYEE_EMPLOYMENT_STATUS
,EMPLOYEE_EMAIL
,EMPLOYEE_DEPARTMENT_ID
,NETWORK_LOGIN as EMPLOYEE_NETWORK_LOGIN
,null as EMPLOYEE_ONSITE_OFFSITE
,null EMPLOYEE_ONSHORE_OFFSHORE
,null EMPLOYEE_CHANNEL_ID
,MANAGER_PREFERRED_NAME as MANAGER_NAME
,MANAGER_DEPARTMENT_ID
,null as MANAGER_SUB_DIVISION_ID
,null as FORECAST_FTES
,BILLABLE_HOURS
,TOTAL_WEEKLY_HOURS as WEEKLY_TOTAL_BILLABLE_HOURS
,BILLABLE_HOURS_SCALED
,CAST(BILLABLE_HOURS_SCALED/40 AS NUMERIC(36,4)) as HEADCOUNT_SCALED
,(CASE
    WHEN left(trim(effort_id),2) = 'WK' THEN 'No'
    WHEN WORK_CATEGORY <> 'PROJ' THEN 'No' ELSE CAPITALIZED END
    ) as CAPITALIZED
,EMPLOYEE_WORKING_TEAM AS EMPLOYEE_SUB_DIVISION_NAME
,null as MANAGER_SUB_DIVISION_NAME
,EMPLOYEE_DEPARTMENT_NAME
,MANAGER_DEPARTMENT_NAME
,EMPLOYEE_HOURLY_RATE
,null as WORKING_TEAM_SUB_DIVISION_SHORT_NAME
,null as BILLED_SUB_DIVISION_SHORT_NAME
,null as EMPLOYEE_SUB_DIVISION_SHORT_NAME
,null as MANAGER_TEAM_SUB_DIVISION_SHORT_NAME
,APPLICATION_ID
,APPLICATION_NAME
,null as BILLED_CHANNEL_ID
,null as BILLED_CHANNEL_NAME
,null as EMPLOYEE_CHANNEL_NAME
,null as APPLICATION_SUB_DIVISION_NAME
,null as APPLICATION_SUB_DIVISION_SHORT_NAME
,null as APPLICATION_CHANNEL_NAME
,REDLINE_PROJECT
,TO_CHAR(REDLINE_ISSUE) AS REDLINE_ISSUE
,REDLINE_ISSUE_SUBJECT
,REDLINE_SPONSORING_BUSINESS_CHANNEL
,EMPLOYEE_TITLE_SHORT as EMPLOYEE_ORG_TIER_DESCRIPTION
,EMPLOYEE_TERMINATION_DATE
,EMPLOYEE_START_DATE
,EMPLOYEE_RECENTLY_TERMED_OR_CURRENTLY_EMPLOYED
,WEEK_START_DATE
,WEEK_END_DATE
,MONTH_OF_WEEK_START_DATE
,MANAGEMENT_HIERARCHY
,MANAGER_EMAIL
,WORK_CATEGORY
,BILLED_DEPARTMENT_ID
,BILLED_DEPARTMENT_NAME
,BREAK_FIX_LIGHTS_ON_ENHANCEMENT
,BILLED_DIVISION_ID
,BILLED_DIVISION_NAME
,REDLINE_PRIMARY_DELIVERY_TEAM
,REDLINE_VERSION_NAME
,redline_version_project_name
,redline_version
FROM "RESOURCE_CAPACITY"."PNMAC"."VW_FORECAST_AND_ACTUAL_COMBINED_INFO_V2B";
