
CREATE OR REPLACE VIEW "RESOURCE_CAPACITY"."PNMAC"."VW_FORECAST_AND_ACTUAL_COMBINED_V2" AS 
SELECT 
  EFFORT_ID
  ,BILLED_DIVISION_ID
  ,BILLED_DEPARTMENT_ID
  ,BILLED_SUB_DIVISION_ID
  ,APPLICATION_ID
  ,APPLICATION_NAME
  ,BILLABLE_HOURS
  ,CAPITALIZED
  ,WORK_CATEGORY
  ,YEAR
  ,QUARTER
  ,MONTH
  ,WEEK
  ,ENTRY_DATE
  ,EMPLOYEE_ID
  ,NETWORK_LOGIN
  ,WORKING_TEAM_SUB_DIVISION_ID
  ,REDLINE_PROJECT
  ,to_char(REDLINE_ISSUE) as REDLINE_ISSUE
  ,REDLINE_ISSUE_SUBJECT
  ,0 as FORECAST
  ,break_fix_lights_on_enhancement
  ,redline_primary_delivery_team
FROM "RESOURCE_CAPACITY"."PNMAC"."VW_ACTUALS_V2"
UNION ALL
SELECT 
  EFFORT_ID
  
  ,BILLED_DIVISION_ID
  ,BILLED_DEPARTMENT_ID
  ,BILLED_SUB_DIVISION_ID

  ,APPLICATION_ID
  ,APPLICATION_NAME
  ,0 as BILLABLE_HOURS
  ,CAPITALIZED
  ,WORK_CATEGORY
  ,YEAR
  ,QUARTER
  ,MONTH
  ,WEEK
  ,ENTRY_DATE
  ,EMPLOYEE_ID
  ,NETWORK_LOGIN
  ,WORKING_TEAM_SUB_DIVISION_ID
  ,REDLINE_PROJECT
  ,TO_CHAR(REDLINE_ISSUE) AS REDLINE_ISSUE
  ,REDLINE_ISSUE_SUBJECT
  ,FORECAST
  ,'N/A' as break_fix_lights_on_enhancement
  ,'Forecast' as redline_primary_delivery_team
FROM "RESOURCE_CAPACITY"."PNMAC"."VW_FORECAST_V2";
